server:
    port: 8885
    servlet:
        context-path: /
spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    application:
        name: 京茶吉鹿的Demo
springdoc:
    swagger-ui:
        path: /docs.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
#    group-configs:
#        - group: 'default'
#          paths-to-match: '/**'
#          packages-to-scan: com.record
knife4j:
    # 开启增强配置
    enable: true
    setting:
        language: zh_cn
        swagger-model-name: 实体类列表
    # 开启Swagger 的Basic认证功能
    basic:
        enable: true
        username: admin
        password: 1234
    documents:
        - name: 标题1
          locations: classpath:markdown/*
          group: default
        - name: 标题2
          locations: classpath:markdown1/*
          group: 用户模块